# Generated by Django 6.0.2 on 2026-06-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cardmonthlylimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar'), ('EUR', 'Euro')], default='BRL', max_length=3, verbose_name='Moeda'),
        ),
    ]
