# Generated by Django 6.0.7 on 2026-07-22 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_account_currency"),
        ("investments", "0003_investment_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="backing_investment",
            field=models.ForeignKey(
                blank=True,
                help_text="Quando definido (apenas para contas do tipo Cartão), o limite disponível passa a ser o valor líquido aplicado nesse investimento, no lugar do Limite do Cartão fixo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backed_accounts",
                to="investments.investment",
                verbose_name="Investimento de garantia",
            ),
        ),
    ]
