# Generated by Django 6.0.5 on 2026-06-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_nfsecredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="default_interface",
            field=models.CharField(
                choices=[
                    ("classic", "Clássico (Django)"),
                    ("react", "Novo App (React)"),
                ],
                default="classic",
                help_text="Define qual painel abrirá por padrão ao fazer login.",
                max_length=20,
                verbose_name="Interface padrão",
            ),
        ),
    ]
