# Generated by Django 6.0.2 on 2026-06-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_default_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='person_type',
            field=models.CharField(blank=True, choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='pf', max_length=2, verbose_name='Tipo de pessoa'),
        ),
    ]
