# Generated by Django 6.0.2 on 2026-07-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_fix_person_type_from_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NfseCredential',
        ),
    ]
