# Generated by Django 6.0.2 on 2026-07-08 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0014_delete_nfsecredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='Endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='Chave p256dh')),
                ('auth', models.CharField(max_length=255, verbose_name='Chave auth')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição push',
                'verbose_name_plural': 'Inscrições push',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant'], name='pushsub_tenant_idx'), models.Index(fields=['user'], name='pushsub_user_idx')],
            },
        ),
    ]
