# Generated by Django 4.2.30 on 2026-07-31 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_delete_nfsecredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0006_todoitem_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=todos.models.todo_attachment_upload_path, verbose_name='Arquivo')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do arquivo')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Hash do conteudo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_attachments', to='tenants.tenant')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='todos.todoitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo de tarefa',
                'verbose_name_plural': 'Anexos de tarefa',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'todo'], name='todo_attach_tenant_idx')],
            },
        ),
    ]
