# Generated by Django 6.0.7 on 2026-08-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_todoattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ('is_done', 'order', '-created_at'), 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AddField(
            model_name='todoitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Posicao do card dentro da coluna do quadro Kanban.', verbose_name='Ordem'),
        ),
    ]
