# Generated by Django 6.0.7 on 2026-08-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_alter_todoitem_options_todoitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arquivada em'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivada'),
        ),
    ]
