# Generated by Django 6.0.2 on 2026-06-29 12:52

import django.db.models.deletion
import drive.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0011_tenant_logo_central_upload_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Título')),
                ('file', models.FileField(upload_to=drive.models.document_upload_path, verbose_name='Arquivo')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tenants.tenantcompany')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'company', '-created_at'], name='drive_docum_tenant__fd6495_idx')],
            },
        ),
    ]
