# Generated by Django 6.0.2 on 2026-06-29 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
        ('tenants', '0011_tenant_logo_central_upload_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Pasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pasta',
                'verbose_name_plural': 'Pastas',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='drive_docum_tenant__fd6495_idx',
        ),
        migrations.AddField(
            model_name='folder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='tenants.tenantcompany'),
        ),
        migrations.AddField(
            model_name='folder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drive.folder'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'company', 'folder', '-created_at'], name='drive_docum_tenant__65ae51_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['tenant', 'company', 'name'], name='drive_folde_tenant__573a75_idx'),
        ),
    ]
