# Generated by Django 6.0.7 on 2026-07-11 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_folder_and_more'),
        ('tenants', '0014_delete_nfsecredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='drive.folder'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['tenant', 'parent'], name='drive_folde_tenant__ec5e2f_idx'),
        ),
    ]
