# Generated by Django 6.0.7 on 2026-07-12 01:12

import drive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_folder_parent_folder_drive_folde_tenant__ec5e2f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=drive.models.document_thumbnail_path, verbose_name='Miniatura'),
        ),
    ]
