# Generated by Django 6.0.7 on 2026-07-12 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_document_thumbnail'),
        ('tenants', '0014_delete_nfsecredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Hash do conteúdo'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'content_hash'], name='drive_docum_tenant__87c4f9_idx'),
        ),
    ]
