# Generated by Django 6.0.7 on 2026-07-12 01:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_document_content_hash_and_more'),
        ('tenants', '0014_delete_nfsecredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='folder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'deleted_at'], name='drive_docum_tenant__d35a31_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['tenant', 'deleted_at'], name='drive_folde_tenant__4f5440_idx'),
        ),
    ]
