# Generated by Django 6.0.7 on 2026-07-31 03:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0014_delete_nfsecredential'),
        ('todos', '0007_todoattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado')], default='draft', max_length=20, verbose_name='Status')),
                ('justification', models.TextField(blank=True, verbose_name='Justificativa')),
                ('objectives', models.TextField(blank=True, verbose_name='Objetivos')),
                ('scope', models.TextField(blank=True, verbose_name='Escopo')),
                ('deliverables', models.TextField(blank=True, verbose_name='Principais entregas')),
                ('assumptions', models.TextField(blank=True, verbose_name='Premissas')),
                ('constraints', models.TextField(blank=True, verbose_name='Restrições')),
                ('risks', models.TextField(blank=True, verbose_name='Riscos preliminares')),
                ('stakeholders', models.TextField(blank=True, verbose_name='Partes interessadas')),
                ('sponsor_name', models.CharField(blank=True, max_length=200, verbose_name='Patrocinador')),
                ('project_manager_name', models.CharField(blank=True, max_length=200, verbose_name='Gerente do projeto')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Início previsto')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Término previsto')),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Orçamento estimado (R$)')),
                ('approved_at', models.DateField(blank=True, null=True, verbose_name='Data de aprovação')),
                ('approved_by_name', models.CharField(blank=True, max_length=200, verbose_name='Aprovado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charters', to='todos.project', verbose_name='Projeto')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_charters', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_charters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Termo de Abertura de Projeto',
                'verbose_name_plural': 'Termos de Abertura de Projeto',
                'ordering': ['-number'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'number'), name='unique_tap_number_per_tenant')],
            },
        ),
    ]
