# Generated by Codex on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcharter",
            name="technologies",
            field=models.TextField(blank=True, verbose_name="Tecnologias utilizadas"),
        ),
    ]
