# Generated by Codex on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap", "0002_projectcharter_technologies"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcharter",
            name="co_responsibles",
            field=models.TextField(blank=True, verbose_name="Co-responsaveis"),
        ),
    ]
