# Generated by Django 6.0.2 on 2026-07-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_unique_category_name_type_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expense_kind',
            field=models.CharField(choices=[('operating', 'Despesa Operacional'), ('cost', 'Custo do Serviço/Produto')], default='operating', help_text='Usado no DRE Gerencial para separar Custo do Serviço de Despesa Operacional. Ignorado para categorias de receita.', max_length=20, verbose_name='Natureza da despesa'),
        ),
    ]
