# Generated by Django 6.0.5 on 2026-06-23 13:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_backfill_personal_tenants"),
        (
            "transactions",
            "0010_remove_closedmonth_unique_closed_month_per_user_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Número")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("issued", "Emitida"),
                            ("paid", "Paga"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Data de emissão")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Vencimento"),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Nome do tomador"),
                ),
                (
                    "client_document",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="CPF / CNPJ"
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail do tomador"
                    ),
                ),
                (
                    "client_address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Endereço"
                    ),
                ),
                (
                    "client_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cidade / UF"
                    ),
                ),
                (
                    "service_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Código do serviço (LC 116)",
                    ),
                ),
                (
                    "service_description",
                    models.TextField(verbose_name="Discriminação dos serviços"),
                ),
                (
                    "gross_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor bruto (R$)"
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Deduções (R$)",
                    ),
                ),
                (
                    "iss_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="ISS (%)",
                    ),
                ),
                (
                    "iss_withheld",
                    models.BooleanField(
                        default=False, verbose_name="ISS retido na fonte"
                    ),
                ),
                (
                    "pis_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="PIS (%)",
                    ),
                ),
                (
                    "cofins_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="COFINS (%)",
                    ),
                ),
                (
                    "csll_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="CSLL (%)",
                    ),
                ),
                (
                    "ir_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="IR (%)",
                    ),
                ),
                (
                    "inss_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="INSS (%)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "paid_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de pagamento"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura",
                "verbose_name_plural": "Faturas",
                "ordering": ["-number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "number"),
                        name="unique_invoice_number_per_tenant",
                    )
                ],
            },
        ),
    ]
