# Generated by Django 6.0.2 on 2026-07-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_issuer_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='nfse_error',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='nfse_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='nfse_requested_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='nfse_status',
        ),
    ]
