# Generated by Django 6.0.2 on 2026-07-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_remove_invoice_nfse_error_remove_invoice_nfse_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='note_issued',
            field=models.BooleanField(default=False, verbose_name='Nota emitida'),
        ),
    ]
