# Generated by Django 6.0.2 on 2026-07-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_note_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('issued', 'Emitida'), ('paid', 'Paga')], default='issued', max_length=20, verbose_name='Status'),
        ),
    ]
