# Generated by Django 6.0.7 on 2026-07-17 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_account_currency'),
        ('tenants', '0014_delete_nfsecredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Chat ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='Vinculado em')),
                ('default_account', models.ForeignKey(blank=True, help_text='Conta usada para lançamentos criados via Telegram.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_links', to='accounts.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_links', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo do Telegram',
                'verbose_name_plural': 'Vínculos do Telegram',
            },
        ),
    ]
