# Generated by Codex on 2026-06-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="Lista")),
                ("color", models.CharField(default="#60a5fa", max_length=7, verbose_name="Cor")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criada em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizada em")),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="note_lists", to="tenants.tenant")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="note_lists", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Lista de anotações",
                "verbose_name_plural": "Listas de anotações",
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "name"), name="unique_note_list_name_per_tenant"),
                ],
            },
        ),
        migrations.AddField(
            model_name="note",
            name="note_list",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notes", to="notes.notelist", verbose_name="Lista"),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["tenant", "note_list", "-updated_at"], name="note_tenant_list_idx"),
        ),
    ]
