# Generated by Claude on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_notelist_note_note_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True, default="", verbose_name="Conteúdo"),
        ),
    ]
