# Generated by Claude on 2026-07-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("notes", "0003_note_content_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteSubtask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("is_done", models.BooleanField(default=False, verbose_name="Concluída")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criada em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizada em")),
                ("note", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subtasks", to="notes.note", verbose_name="Anotação")),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="note_subtasks", to="tenants.tenant")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="note_subtasks", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Subtarefa",
                "verbose_name_plural": "Subtarefas",
                "ordering": ("is_done", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="notesubtask",
            index=models.Index(fields=["tenant", "note"], name="note_subtask_tenant_note_idx"),
        ),
    ]
