# Generated by Django 6.0.7 on 2026-08-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notesubtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='visibility',
            field=models.CharField(choices=[('public', 'Pública'), ('private', 'Privada')], default='public', max_length=10, verbose_name='Visibilidade'),
        ),
    ]
